language: perl
script: HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
install:
  - cpanm "Exporter::Tiny" "PadWalker" "Parse::Keyword" "Smart::Match" "Test::More" "Test::Requires" "Types::Standard" "match::simple"
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change
